curl error handling, remove assetapi from migration path

diff --git a/.github/workflows/crm-slip-cicd.yaml b/.github/workflows/crm-slip-cicd.yaml
--- a/.github/workflows/crm-slip-cicd.yaml
+++ b/.github/workflows/crm-slip-cicd.yaml
@@ -41,7 +41,7 @@ jobs:
             echo "MY_REF=dev" >> $GITHUB_ENV
             echo "DEPLOY_PATH=${{ env.MY_ORG }}/int-dev/${{ env.APP_NAME }}" >> $GITHUB_ENV
           fi
-
+      
       - name: Create new project from github
         run: |
           response=$(curl -o /dev/null -w "%{http_code}" --location --request POST '${{ env.URL }}/api/1/rest/public/project/create-project/${{ env.DEPLOY_PATH }}' \
@@ -53,21 +53,23 @@ jobs:
               }')
           echo response=$response
           if [[ $response -gt 299 ]]; then
-            echo "HTTP request failed with status code $response"
+            echo "create-project request failed with status code $response"
             echo "MIGRATE=true" >> $GITHUB_ENV
             exit 1
           fi
         continue-on-error: true
 
       - name: Delete project build folder
+        if: ${{ env.MIGRATE }}
         run: |
-          curl --location --request DELETE '${{ env.URL }}/api/1/rest/public/assetapi/project/${{ env.BUILD_PATH }}' \
+          curl  --location --request DELETE '${{ env.URL }}/api/1/rest/public/assetapi/project/${{ env.BUILD_PATH }}' \
             --header 'Content-Type: application/json' \
-            --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}' 
+            --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}'
 
       - name: Create project build folder
+        if: ${{ env.MIGRATE }}
         run: |
-          curl --location --request POST '${{ env.URL }}/api/1/rest/public/assetapi/project/migrate/${{ env.BUILD_PATH }}' \
+          response=(curl -o /dev/null -w "%{http_code}" --location --request POST '${{ env.URL }}/api/1/rest/public/assetapi/project/migrate/${{ env.BUILD_PATH }}' \
             --header 'Content-Type: application/json' \
             --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}' \
             --data-raw '{
@@ -79,25 +81,33 @@ jobs:
                         "subject": "roger.davies@asu.edu"
                     }
                 ]
-            }'
+            }')
+          echo response=$response
+          if [[ $response -gt 299 ]]; then
+            echo "Build path folder request failed with status code $response"
+            exit 1
+          fi
 
       - name: Checkout Project from Github to project build folder
         if: ${{ env.MIGRATE }}
         run: |
-          echo "MIGRATE?: ${{ env.MIGRATE }}" 
-          curl --location --request POST '${{ env.URL }}/api/1/rest/public/project/checkout/${{ env.BUILD_PATH }}' \
+          response=(curl -o /dev/null -w "%{http_code}" --location --request POST '${{ env.URL }}/api/1/rest/public/project/checkout/${{ env.BUILD_PATH }}' \
             --header 'Content-Type: application/json' \
             --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}' \
             --data-raw  '{
                 "repo": "${{ github.repository }}",
                 "ref": "${{ env.MY_REF }}"
-              }'
+              }')
+          echo response=$response
+          if [[ $response -gt 299 ]]; then
+            echo "Project checkout request failed with status code $response"
+            exit 1
+          fi
 
       - name: Migrate project from github or migrate if exists
         if: ${{ env.MIGRATE }}
         run: |
-          echo "MIGRATE?: ${{ env.MIGRATE }}" 
-          curl --location --request POST '${{ env.URL }}/api/1/rest/public/assetapi/project/migrate/${{ env.BUILD_PATH }}' \
+          response=(curl -o /dev/null -w "%{http_code}" --location --request POST '${{ env.URL }}/api/1/rest/public/project/migrate/${{ env.BUILD_PATH }}' \
           --header 'Content-Type: application/json' \
           --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}' \
           --data-raw '{
@@ -105,4 +115,9 @@ jobs:
               "asset_types" : ["File", "Job", "Pipeline", "Policy"],
               "duplicate_check" : false,
               "async" : false
-          }'
+          }')
+          echo response=$response
+          if [[ $response -gt 299 ]]; then
+            echo "Migrate project request failed with status code $response"
+            exit 1
+          fi
