add error trapping for all curls

diff --git a/.github/workflows/crm-slip-cicd.yaml b/.github/workflows/crm-slip-cicd.yaml
--- a/.github/workflows/crm-slip-cicd.yaml
+++ b/.github/workflows/crm-slip-cicd.yaml
@@ -21,16 +21,10 @@ env:
 jobs:
   build: 
     runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: benjlevesque/short-sha@v3.0
-        id: short-sha
-        env:
-          SHA: ${{ steps.short-sha.outputs.sha }}
-          
+    steps:          
       - name: Set deploy vars
         run: |
-          echo "BUILD_PATH=${{ env.MY_ORG }}/CICD/${{ env.APP_NAME }}-${{ env.SHA }}" >> $GITHUB_ENV
+          echo "BUILD_PATH=${{ env.MY_ORG }}/CICD/${{ env.APP_NAME }}" >> $GITHUB_ENV
           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
             echo "MY_REF=main" >> $GITHUB_ENV
             echo "DEPLOY_PATH=${{ env.MY_ORG }}/int-prod/${{ env.APP_NAME }}" >> $GITHUB_ENV
@@ -66,7 +60,7 @@ jobs:
       - name: Create project build folder
         if: ${{ env.MIGRATE }}
         run: |
-          curl -s --location --request POST '${{ env.URL }}/api/1/rest/public/assetapi/project/${{ env.BUILD_PATH }}' \
+          if curl -s --fail --location --request POST '${{ env.URL }}/api/1/rest/public/assetapi/project/${{ env.BUILD_PATH }}' \
             --header 'Content-Type: application/json' \
             --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}' \
             --data-raw '{
@@ -78,23 +72,33 @@ jobs:
                         "subject": "roger.davies@asu.edu"
                     }
                 ]
-            }'
+            }'; then
+            echo "create project build folder request succeeded"
+          else 
+            echo "create project build folder request failed"
+            exit 1
+          fi
 
       - name: Checkout Project from Github to project build folder
         if: ${{ env.MIGRATE }}
         run: |
-          curl -s --location --request POST '${{ env.URL }}/api/1/rest/public/project/checkout/${{ env.BUILD_PATH }}' \
+          if curl -s --fail --location --request POST '${{ env.URL }}/api/1/rest/public/project/checkout/${{ env.BUILD_PATH }}' \
             --header 'Content-Type: application/json' \
             --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}' \
             --data-raw  '{
                 "repo": "${{ github.repository }}",
                 "ref": "${{ env.MY_REF }}"
-              }'
+              }'; then
+            echo "checkout project request succeeded"
+          else 
+            echo "checkout project request request failed"
+            exit 1
+          fi
 
-      - name: Migrate project from github or migrate if exists
+      - name: Migrate project
         if: ${{ env.MIGRATE }}
         run: |
-          curl -s --location --request POST '${{ env.URL }}/api/1/rest/public/project/migrate/${{ env.BUILD_PATH }}' \
+          if curl -s --fail --location --request POST '${{ env.URL }}/api/1/rest/public/project/migrate/${{ env.BUILD_PATH }}' \
           --header 'Content-Type: application/json' \
           --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}' \
           --data-raw '{
@@ -102,4 +106,16 @@ jobs:
               "asset_types" : ["File", "Job", "Pipeline", "Policy"],
               "duplicate_check" : false,
               "async" : false
-          }'
+          }'; then
+            echo "migrate project request succeeded"
+          else 
+            echo "migrate project request request failed"
+            exit 1
+          fi
+
+      - name: Clean-up project build folder
+        if: ${{ env.MIGRATE }}
+        run: |
+          curl -s --location --request DELETE '${{ env.URL }}/api/1/rest/public/assetapi/project/${{ env.BUILD_PATH }}' \
+            --header 'Content-Type: application/json' \
+            --header 'Authorization: Basic ${{ secrets.SNAPLOGIC_HTTP_BASIC_AUTH }}'
